/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import dragDropContentTypesStrapi5 from "@yunusemrejs/drag-drop-content-types-strapi5/strapi-admin";
import standardStrapiToolkit from "../../src/plugins/standard-strapi-toolkit/./dist/admin/index.mjs";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "drag-drop-content-types-strapi5": dragDropContentTypesStrapi5,
    "standard-strapi-toolkit": standardStrapiToolkit,
  },
});
